# Generated by Django 5.0.6 on 2024-06-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
