# Generated by Django 5.0.6 on 2024-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_alter_taskobject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
