# Generated by Django 5.0.6 on 2024-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_alter_taskobject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_annotator',
            field=models.BooleanField(default=False),
        ),
    ]
