# Generated by Django 5.0.6 on 2024-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0005_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtaskresult',
            name='tagged_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
